server {
    listen 80;
    listen [2a05:f480:1800:a57::80]:80;
    server_name my-dev.repraesent.com;

    include vhosts/acme.inc;

    location / {
        return 301 https://my-dev.repraesent.com$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [2a05:f480:1800:a57::80]:443 ssl;
    server_name my-dev.repraesent.com;

    ssl_certificate     /usr/local/etc/ssl/my-dev.repraesent.com/fullchain.pem;
    ssl_certificate_key /usr/local/etc/ssl/my-dev.repraesent.com/key.pem;

    location = /hooks/b7e2f8a7970014936c6acaba744c86e3 {
        limit_except POST { deny all; }
        proxy_pass http://10.188.0.102;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://10.188.0.102;
    }
}
